name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Usar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Ir a la carpeta del proyecto
      run: cd backend

    - name: Instalar dependencias
      run: npm install
      working-directory: ./MERN/TItzae

    - name: Ejecutar pruebas
      run: npm test
      working-directory: ./MERN/TItzae
